apiVersion: apps/v1
kind: Deployment

metadata: 
  name: first-deployment


spec:
  selector:
    matchLabels:
      app: Alaa

  replicas: 3
  template: 
    metadata:
      name: my-first-pod
      labels: 
        app: Alaa
    spec:
      containers:
        - image: nginx:alpine
          name: nginx-container
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi"  