apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels: 
    app: Alaa
spec:
  containers:
    - image: nginx:alpine
      name: nginx-container
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "100Mi"